### ISSUE TITLE
Wonky placeholder behavior when dragging rows within a table

### ISSUE THREAD

**Issue by livfwd** [Deveo/ember-drag-sort#12]
Thanks for your incredible work on this addon!

It seems like the :before :after pseudo-elements break the table layout and put the placeholder in unexpected places when dragging rows within a table.  Are there any known workarounds for this? If not, I'd like to put a request in for full support of dragging rows within a table.

**Comment by lolmaus** [comment]
Hey @livfwd! `ember-drag-sort` developer here. Thank you for kind words, it motivates a lot!

`ember-drag-sor`t uses a simple CSS technique to render the placeholder: `:before` and `:after` pseudoelements.

Unfortunately, this doesn't work with HTML tables because table semantics are very restrictive. To work around this problem, top/bottom padding on table cells can be used instead of selectors.

This is not a great solution because padding appears inside table cells. If you want your cells to have borders, you'll have to apply them to inner elements instead.

I've added tables to the [demo](https://deveo.github.io/ember-drag-sort/), please have a look.

If this approach does not suit you, unfortunately, this addon currently cannot offer anything else. You'll have to either revert to `div`s or use another drag-sorting addon.

Hypothetically, I can imagine `ember-drag-sort` inject an extra `<tr>` list element for a placeholder, but I'm not planning to develop it myself. The goal of `ember-drag-sort` in the first place was to make it as simple as possible, avoiding array manipulations and DOM rerenders during dragging.

If you're willing to contribute, I can explain a direction that I might find acceptable to merge.
