### ISSUE TITLE
Determining new parent for nested lists

### ISSUE THREAD

**Issue by andrewsyd** [Deveo/ember-drag-sort#13]
For a nested list, is there a way to determine in the dragEnd action which "sub-list" the item has been dropped into? (e.g. a class name, id etc)

In my scenario, I am sorting ember data records that can belong to each other (i.e. a nested, 'tree' structure). When I drag one nested record "into" another (making the dragged record a child of the second record), I need to update the parent attribute in ember-data. My question is, how do you pass some id of the second record (the new parent) to the dragEnd action?

Is this even possible?

**Comment by lolmaus** [comment]
Hey, @andrewsyd!

Thank you for trying out `ember-drag-sort` and sharing your use case.

I've replied to your question on StackOverflow, please have a look: https://stackoverflow.com/q/47266348/901944

I've updated the support policy for this project: support requests should be performed via StackOverflow and the `ember-drag-sort` tag.

I'm closing this issue, assuming it's resolved. We can still continue the discussion in the closed issue.

If you try my suggestions report your problem is still unresolved, I'll reopen it.

Good luck and don't hesitate to ask any other questions.

**Comment by lolmaus** [comment]
> Thanks so much for your detailed response, Andrey. I am the original poster and had already posted the same question here

@andrewsyd, I missed it because the `ember-drag-sort` tag didn't exist on SO and I wasn't subscribed.

You should make effort to gain some initial rep on SO, so that you can upvote and comment fully. It's not that hard. While you can't, let's continue the discussion here. I didn't mean to make it harder for you.

> Now I'm more confused than before, ha! Not quite sure where 'isParent' came from.

Initially you said: "*I need to update the parent attribute*". So I just renamed `parent` to `isParent` to make a distinction from the `parent` relationship.


> All I am attempting to do is the following:
> 
> Move one object from List A (representing the parent record) to any of lists B, C or D.
When it is dragged into List B, I need to somehow identify which list it actually is, so I can tell ember data that the record now belongs to List B. As far as I can tell, by default, dragEnd has no idea which list the "target list"/receiving list actually is.
Think of it like dragging one file from one folder to another folder. When moving the file to another folder, you are saying that the file now belongs to that new folder. How can I tell which "folder" is the new one?
> 
> Does this make more sense?

It looks like you're confusing terms. By "*parent attribute*" do you actually mean "*parent relationship*"? And by "*which list the target list actually is*" you mean *which record the target list belongs to*?

As I mentioned in my SO answer, Ember Data performs automatic relationship bookkeeping. To enable it, you need to define inverse relationships:

```js
export default Model.extend({  
  parent: belongsTo('item', {inverse: 'children', async: false}),
  children: hasMany('item', {inverse: 'parent',   async: false}),
})
```

Now, a standard `dragEnd` action is sufficient:

```js
  actions : {
    dragEnd ({sourceList, sourceIndex, targetList, targetIndex}) {
      if (sourceList === targetList && sourceIndex === targetIndex) return

      const draggedItem = sourceList.objectAt(sourceIndex)

      sourceList.removeAt(sourceIndex)
      targetList.insertAt(targetIndex, draggedItem)
    },
  },
```

In this action, the `sourceList` is the `oldParent.children` relationship, and `targetList` is the `newParent.children` relationship. By doing `sourceList.objectAt(sourceIndex)` you obtain the dragged record.

When you manipulate the `children` relationship, Ember Data automatically updates the other end of the relationship, so you don't need to update the `parent` relationship manually.

Here's a demo: https://ember-twiddle.com/f1c737d3bc106cb9cca071fd01fe334f?openFiles=controllers.application.js%2C

If this still doesn't resolve your issue, I have to insist that you create your own demo of the issue via Ember Twiddle. You can start off my twiddle by forking [my gist](https://gist.github.com/lolmaus/f1c737d3bc106cb9cca071fd01fe334f), copying the hash from the URL of the new gist and inserting it into the Ember Twiddle URL.

**Comment by andrewsyd** [comment]
I see what's happened now, so for the record...

I was first sorting the child items in my component with:
~~~~
  ...
  
  childrenSorting: ['rowOrder'],
  sortedChildren: Ember.computed.sort(
    'item.children',
    'childrenSorting'),
  
  ...
~~~~

... and passing `sortedChildren` instead of `item.children` to the `drag-sort-list` component as `items`. Once I get rid of that (probably flawed) sorting method and just pass in `item.children`, the parent relationship updates by itself. This not working for me the way I had it is why I thought I had to manually update the relationship.

So the issue for me to figure out now is really how to properly display the items in order of their `rowOrder` attribute in the first place, which of course is an entirely different question :)

And yes, I did mean 'parent relationship' before.

(Thanks again @lolmaus for your help, your advice - and your patience! Much appreciated.)

**Comment by lolmaus** [comment]
All right, I think I understand your problem now.

The easiest way to pass the parent record into the drag end function is to make it a property on the array:

```js
export default Model.extend({  
  rowOrder: attr('number'),
  parent: belongsTo('item', {inverse: 'children', async: false}),
  children: hasMany('item', {inverse: 'parent',   async: false}),
  
  childrenSortOrder: ['rowOrder:asc'],
  childrenSorted: Ember.computed.sort('children', 'childrenSortOrder'),
  
  childrenSortedBound: Ember.computed('childrenSorted.[]', function () {
    const children = this.get('childrenSorted').slice() // Making a shallow copy of the array, because CPs should never have side effects
    children.__parent__ = this
    return children
  })
})
```

This indeed feels hacky, but the approach is legit.

Now you need to pass the `childrenSortedBound` array into the `drag-sort-list` component, but in the `dragEnd` action you need to manipulate the original `children` list. You can access it like this:

```js
      targetList
        .__parent__
        .get('children')
      	.addObject(draggedItem)
```

The whole `dragEnd` action can look like this:

```js
{
  actions : {
    dragEnd ({sourceList, sourceIndex, targetList, targetIndex}) {
      if (sourceList === targetList && sourceIndex === targetIndex) return

      const draggedItem = sourceList.objectAt(sourceIndex)

      // Updating rowOrder of items in source list
      sourceList
        .slice(sourceIndex + 1)
      	.forEach(item => {
          const rowOrder = item.get('rowOrder')
          item.set('rowOrder', rowOrder - 1)
        })

      // Updating rowOrder of items in target list
      targetList
        .slice(targetIndex)
      	.forEach(item => {
          const rowOrder = item.get('rowOrder')
          item.set('rowOrder', rowOrder + 1)
        })
      
      // Updating rowOrder of dragged item
      draggedItem.set('rowOrder', targetIndex)
      
      // Moving dragged item into the target list
      // We can't do it directly because the list is a derived one,
      // so we need to access the original list using a hack from the model
      targetList
        .__parent__
        .get('children')
      	.addObject(draggedItem)
      
      // Note, that we don't need to remove the item from the source list.
      // Ember Data does this automatically because our relationship is
      // two-way.
    },
  },
}
```

Demo: https://ember-twiddle.com/0a52fd0d8e8a81cdca008023f5798cdf?numColumns=2&openFiles=controllers.application.js%2Ccontrollers.application.js

I hope this resolves your use case.

PS We've spend a lot of time figuring out what you actually need. This short guide will help you save a lot of time time (both yours and maintainer's) when asking questions: [The XY Problem](http://xyproblem.info/). Also, please be careful and precise with terms: the *attribute* vs *relationship* confusion lead me in a totally different direction, making me spend time on two demos unrelated to your problem.

PPS Please create a [new StackOverflow question](https://stackoverflow.com/questions/ask?tags=ember.js,ember-data,ember-drag-sort) where you ask the final version of your question. Make effort for the question to be correct and explicit, don't just copy what you already said. I will repost my answer there. Everyone will benefit from it: you and I will get a few SO rep points, and the `ember-drag-sort` SO tag will receive a new use case study.

PPPS I've noticed that nested list behavior is wonky: sometimes the placeholder jumps to and fro while you hold the pointer still. If you experience that, please open an issue.

**Comment by lolmaus** [comment]
> PPPS I've noticed that nested list behavior is wonky: sometimes the placeholder jumps to and fro while you hold the pointer still. If you experience that, please open an issue.

I've just fixed this in ea15cbe7b1dbb15414c9c456acae417d4a53f767, released as `v1.1.1`.

**Comment by andrewsyd** [comment]
Sorry @lolmaus, will do. New to this! This works for me now, thanks again for your help.

**Comment by lolmaus** [comment]
@rwwagner90 has implemented the [additional arguments](https://github.com/kaliber5/ember-drag-sort/#passing-additional-arguments) feature that lets you achieve this in a much simpler and more straightforward way.
